// Autogenerated from Pigeon (v3.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class F2NMessage;
@class N2FMessage;

@interface F2NMessage : NSObject
+ (instancetype)makeWithMsg:(nullable NSString *)msg;
@property(nonatomic, copy, nullable) NSString * msg;
@end

@interface N2FMessage : NSObject
+ (instancetype)makeWithMsg2:(nullable NSString *)msg2;
@property(nonatomic, copy, nullable) NSString * msg2;
@end

/// The codec used by FlutterMessage.
NSObject<FlutterMessageCodec> *FlutterMessageGetCodec(void);

@protocol FlutterMessage
- (void)flutterSendMessageMsg:(F2NMessage *)msg error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FlutterMessageSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FlutterMessage> *_Nullable api);

/// The codec used by NativeMessage.
NSObject<FlutterMessageCodec> *NativeMessageGetCodec(void);

@interface NativeMessage : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)nativeSendMessageMsg:(N2FMessage *)msg completion:(void(^)(NSError *_Nullable))completion;
@end
NS_ASSUME_NONNULL_END
