// Autogenerated from Pigeon (v3.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name
// @dart = 2.12
import 'dart:async';
import 'dart:typed_data' show Uint8List, Int32List, Int64List, Float64List;

import 'package:flutter/foundation.dart' show WriteBuffer, ReadBuffer;
import 'package:flutter/services.dart';

class F2NMessage {
  F2NMessage({
    this.msg,
  });

  String? msg;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['msg'] = msg;
    return pigeonMap;
  }

  static F2NMessage decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return F2NMessage(
      msg: pigeonMap['msg'] as String?,
    );
  }
}

class N2FMessage {
  N2FMessage({
    this.msg2,
  });

  String? msg2;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['msg2'] = msg2;
    return pigeonMap;
  }

  static N2FMessage decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return N2FMessage(
      msg2: pigeonMap['msg2'] as String?,
    );
  }
}

class _FlutterMessageCodec extends StandardMessageCodec {
  const _FlutterMessageCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is F2NMessage) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else 
{
      super.writeValue(buffer, value);
    }
  }
  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:       
        return F2NMessage.decode(readValue(buffer)!);
      
      default:      
        return super.readValueOfType(type, buffer);
      
    }
  }
}

class FlutterMessage {
  /// Constructor for [FlutterMessage].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FlutterMessage({BinaryMessenger? binaryMessenger}) : _binaryMessenger = binaryMessenger;

  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _FlutterMessageCodec();

  Future<void> flutterSendMessage(F2NMessage arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.FlutterMessage.flutterSendMessage', codec, binaryMessenger: _binaryMessenger);
    final Map<Object?, Object?>? replyMap =
        await channel.send(<Object?>[arg_msg]) as Map<Object?, Object?>?;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyMap['error'] != null) {
      final Map<Object?, Object?> error = (replyMap['error'] as Map<Object?, Object?>?)!;
      throw PlatformException(
        code: (error['code'] as String?)!,
        message: error['message'] as String?,
        details: error['details'],
      );
    } else {
      return;
    }
  }
}

class _NativeMessageCodec extends StandardMessageCodec {
  const _NativeMessageCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is N2FMessage) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else 
{
      super.writeValue(buffer, value);
    }
  }
  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:       
        return N2FMessage.decode(readValue(buffer)!);
      
      default:      
        return super.readValueOfType(type, buffer);
      
    }
  }
}
abstract class NativeMessage {
  static const MessageCodec<Object?> codec = _NativeMessageCodec();

  void nativeSendMessage(N2FMessage msg);
  static void setup(NativeMessage? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.NativeMessage.nativeSendMessage', codec, binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null, 'Argument for dev.flutter.pigeon.NativeMessage.nativeSendMessage was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final N2FMessage? arg_msg = (args[0] as N2FMessage?);
          assert(arg_msg != null, 'Argument for dev.flutter.pigeon.NativeMessage.nativeSendMessage was null, expected non-null N2FMessage.');
          api.nativeSendMessage(arg_msg!);
          return;
        });
      }
    }
  }
}
